### ISSUE TITLE
readme.md link  is missing

### ISSUE THREAD

**Issue by kjw3898** [HansKrywaa/cordova-plugin-dfu-update#1]
in readme.md
https://www.nordicsemi.com/DocLib/Content/SDK_Doc/nRF5_SDK/v12-2-0/lib_bootloader_dfu
this link show 404 page

and 
in readme.md
Android: Cordova-android of at least 8.0.0
it's not right info
according to plugin.xml 
it seem to be >=9.0.0

**Comment by HansKrywaa** [comment]
Readme updated and `Cordova-android` fixed in new Version: **[1.0.6](https://www.npmjs.com/package/cordova-plugin-dfu-update)**
