### ISSUE TITLE
Update happening twice O.o

### ISSUE THREAD

**Issue by Funkelfetisch** [HansKrywaa/cordova-plugin-dfu-update#3]
I implemented your plugin as a replacement for the fxe-gear fork.

On Android, the update works perfectly, my device starts the new firmware, runs for 1 or 2 seconds, BUT THEN goes back to boot loader, and 3 minutes later (the duration of a firmware update) starts again. This time it stays like that.
If I kill the android app during those few seconds, my hardware keeps working, so it must be something with the app
My Ionic5 application console.logs only show the first update ending successfully, but nothing at all about a second update running, so I must assume it's something outside angular, presumably the Java part.

Any idea what's happening?
Maybe some kind of automatic retry due to a falsely detected fail of the first update??

A trimmed-down version of the code I use:

```
DfuUpdate.updateFirmware(
      (data) => {
        console.info('FIRMWARE UPDATE: Status: ' + data.status);
        if (data.status === 'dfuCompleted') {
          console.info('FIRMWARE UPDATE: Success!');
        }
      },
      (error) => {
        console.error(error);
      }, filename,
      this.upgradeTarget);
  }
```

**Comment by HansKrywaa** [comment]
How do you see that the Update starts again? Does the `'FIRMWARE UPDATE: Status: ' + data.status` Logs appear again after first success?

**Comment by Funkelfetisch** [comment]
by watching the LEDs on my controller. They clearly signal the controller going back into bootloader (blue), and a second later into "receiving incoming DFU" (red).
No, the log doesn't show any more regarding updates after the first one. 
The log isn't halted or broken though, other (non-DFU-related) log lines still appear.

**Comment by HansKrywaa** [comment]
I can't reproduce that. I created this Fork for a App of my Company and it works well 🤔
