### ISSUE TITLE
Unsupported Swift Version

### ISSUE THREAD

**Issue by devlyn37** [HansKrywaa/cordova-plugin-dfu-update#4]
After adding this plugin and building my project, I see this message in Xcode.

<img width="423" alt="Screen Shot 2020-07-14 at 4 20 06 PM" src="https://user-images.githubusercontent.com/17352012/87485633-185f2b80-c5ee-11ea-88ff-e20868cdc0c9.png">

I'm using Xcode version 11.5

**Comment by HansKrywaa** [comment]
I don't understand the Error as it says the migration should work from 10.1 and you use 11.5. If you could do some research about this problem and let me know, would be really helpfull

**Comment by devlyn37** [comment]
I figured out the issue, the bridging header file wasn't being merged properly. It was my environment not being set up correctly.
